import {createHash} from 'node:crypto';import {SiteSchema,ProfileSchema,NewsSchema} from './studio-schema.mjs';import {validateConfig} from '../src/lib/customization.js';import {contentNames,mediaLimit,config} from './studio-config.mjs';import {fail} from './studio-security.mjs';import {head,snapshot,readFile,github,repoPath} from './studio-github.mjs';
export const assetPattern=/^\/media\/(?:[A-Za-z0-9_-]+\/)*[A-Za-z0-9_.-]+\.(?:webp|png|jpe?g|pdf)$/i;
export function mediaPath(p){if(typeof p!=='string'||!assetPattern.test(p)||p.includes('..'))fail(400,'MEDIA','مسار وسائط غير مسموح.');return 'public'+p}
export function references(bundle){const s=bundle.site;return [...new Set([s.logo,s.visionLogo,s.heroImage,...s.heroSlides.map(x=>x.image),...s.countries.map(x=>x.flagImage),...bundle.news.map(x=>x.image).filter(Boolean),...bundle.profiles.map(x=>x.file)])]}
function safeObject(v,depth=0){if(depth>24)fail(400,'DATA','بيانات متداخلة أكثر من المسموح.');if(typeof v==='string'&&v.length>150000)fail(400,'DATA','النص طويل جدًا.');if(v&&typeof v==='object'){if(Array.isArray(v)&&v.length>200)fail(400,'DATA','عدد العناصر كبير جدًا.');for(const k of Object.keys(v)){if(['__proto__','prototype','constructor'].includes(k))fail(400,'DATA','مفتاح بيانات غير مسموح.');safeObject(v[k],depth+1)}}}
export function validateBundle(b){safeObject(b);if(!b||Array.isArray(b)||Object.keys(b).sort().join(',')!==[...contentNames].sort().join(','))fail(400,'DATA','أقسام الإعدادات غير مكتملة.');try{SiteSchema.parse(b.site);ProfileSchema.array().parse(b.profiles);NewsSchema.array().parse(b.news);validateConfig(b);}catch{fail(400,'VALIDATION','بعض الحقول غير صالحة. راجع النصوص المطلوبة، الأرقام، الألوان والتواريخ قبل الحفظ.');}if(!Array.isArray(b.site.heroSlides)||b.site.heroSlides.length>20)fail(400,'SLIDES','حد صور السلايدر الإضافية 20.');references(b).forEach(mediaPath);const imageRefs=[b.site.logo,b.site.visionLogo,b.site.heroImage,...b.site.heroSlides.map(x=>x.image),...b.site.countries.map(x=>x.flagImage),...b.news.map(x=>x.image).filter(Boolean)];if(imageRefs.some(p=>/\.pdf$/i.test(p)))fail(400,'MEDIA','حقول الصور لا تقبل PDF.');return b}
export async function loadBundle(token,snap){const entries=await Promise.all(contentNames.map(async name=>{const bytes=await readFile(token,snap,'src/data/'+name+'.json');let value;try{value=JSON.parse(bytes.toString('utf8'))}catch{fail(400,'JSON','ملف إعدادات غير صالح: '+name)}return [name,value]}));return validateBundle(Object.fromEntries(entries))}
function binary(data,path){if(typeof data!=='string')fail(400,'UPLOAD','وسائط غير صالحة.');const m=data.match(/^data:(image\/(?:png|jpeg|webp)|application\/pdf);base64,([A-Za-z0-9+/]*={0,2})$/);if(!m)fail(400,'UPLOAD','يُسمح فقط بصور PNG/JPEG/WebP وملفات PDF.');const bytes=Buffer.from(m[2],'base64');if(!bytes.length||bytes.length>mediaLimit||bytes.toString('base64')!==m[2])fail(413,'UPLOAD','الحد الأقصى لكل ملف جديد 2 ميجابايت.');const ext=path.split('.').pop().toLowerCase();const valid=m[1]==='image/png'&&ext==='png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||m[1]==='image/jpeg'&&['jpg','jpeg'].includes(ext)&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255||m[1]==='image/webp'&&ext==='webp'&&bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP'||m[1]==='application/pdf'&&ext==='pdf'&&bytes.toString('ascii',0,5)==='%PDF-';if(!valid)fail(400,'UPLOAD','محتوى الملف لا يطابق نوعه.');return bytes}
const gitHash=bytes=>createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex');
export async function saveBundle(token,input){if(!input||!/^([0-9a-f]{40})$/.test(input.baseSha||''))fail(400,'REF','نسخة الأساس مفقودة. حمّل الموقع أولًا.');validateBundle(input.bundle);const uploads=input.uploads||{};if(typeof uploads!=='object'||Array.isArray(uploads)||Object.keys(uploads).length>12)fail(400,'UPLOAD','أرسل 12 ملفًا كحد أقصى في الدفعة.');const current=await head(token);if(current!==input.baseSha)fail(409,'CONFLICT','وصل تعديل أحدث من CMS أو GitHub. صدّر تعديلاتك ثم حمّل آخر نسخة قبل إعادة تطبيقها.');const snap=await snapshot(token,current);const refs=new Set(references(input.bundle)),pending=[];
 for(const [p,data]of Object.entries(uploads)){const path=mediaPath(p);if(!/^\/media\/upload-[A-Za-z0-9.-]+$/.test(p)||!refs.has(p))fail(400,'UPLOAD','يجب أن يكون الملف الجديد مستخدمًا وله اسم رفع آمن.');const bytes=binary(data,p),existing=snap.files.get(path);if(existing){if(existing.sha!==gitHash(bytes))fail(409,'MEDIA_CONFLICT','يوجد ملف مختلف بنفس الاسم. أعد رفعه باسم جديد.');}else pending.push({path,bytes})}
 for(const p of refs){const path=mediaPath(p);if(!snap.files.has(path)&&!pending.some(x=>x.path===path))fail(400,'MISSING_MEDIA','ملف مشار إليه غير موجود: '+p)}
 const changes=[];
 for(const name of contentNames){const path='src/data/'+name+'.json';const existing=await readFile(token,snap,path),next=Buffer.from(JSON.stringify(input.bundle[name],null,2)+'\n');if(JSON.stringify(JSON.parse(existing.toString()))!==JSON.stringify(input.bundle[name]))changes.push({path,bytes:next})}
 changes.push(...pending);if(!changes.length)return {sha:current,changed:[],unchanged:true};
 // Prepare immutable Git objects first; only the final non-forced ref update publishes anything.
 const tree=[];for(const change of changes){const blob=await github(token,repoPath+'/git/blobs','POST',{content:change.bytes.toString('base64'),encoding:'base64'});tree.push({path:change.path,mode:'100644',type:'blob',sha:blob.sha})}
 const newTree=await github(token,repoPath+'/git/trees','POST',{base_tree:snap.treeSha,tree});const commit=await github(token,repoPath+'/git/commits','POST',{message:'Update site content via Jasr Studio',tree:newTree.sha,parents:[current]});await github(token,repoPath+'/git/refs/heads/'+config.branch,'PATCH',{sha:commit.sha,force:false});return {sha:commit.sha,changed:changes.map(x=>x.path),commitUrl:'https://github.com/'+config.repo+'/commit/'+commit.sha,unchanged:false}}
